name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g firebase-tools

      - name: Setup Google Cloud credentials
        env:
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SIDELINE_SIDEKICK_APP }}
        run: echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > firebase-service-account.json

      - name: Install and build frontend
        run: |
          cd admin-portal-frontend/
          npm ci
          npm run build

      - name: Install backend dependencies
        run: |
          cd backend/
          npm ci

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $PWD/firebase-service-account.json
        run: firebase deploy --only hosting,functions
