name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g firebase-tools

      - name: Install and build frontend
        run: |
          cd admin-portal-frontend/
          npm ci
          npm run build

      - name: Install backend dependencies
        run: |
          cd backend/
          npm ci

      - name: Deploy to Firebase
        run: firebase deploy --only hosting,functions --token "${{ secrets.FIREBASE_TOKEN }}"
